#ifndef INSANE_CONFIGURATION_CPP_LANGUAGE_HPP_INCLUDE
#define INSANE_CONFIGURATION_CPP_LANGUAGE_HPP_INCLUDE

#define INSANE_CPP_NO_STANDARD_COMPLIANT 0x00
#define INSANE_CPP_11_STANDARD_COMPLIANT 0x01
#define INSANE_CPP_14_STANDARD_COMPLIANT 0x02
#define INSANE_CPP_17_STANDARD_COMPLIANT 0x04
#define INSANE_CPP_2X_STANDARD_COMPLIANT 0x08

#define INSANE_CPP_NO_STANDARD (INSANE_CPP_NO_STANDARD_COMPLIANT)
#define INSANE_CPP_11_STANDARD (INSANE_CPP_NO_STANDARD | INSANE_CPP_11_STANDARD_COMPLIANT)
#define INSANE_CPP_14_STANDARD (INSANE_CPP_11_STANDARD | INSANE_CPP_14_STANDARD_COMPLIANT)
#define INSANE_CPP_17_STANDARD (INSANE_CPP_14_STANDARD | INSANE_CPP_17_STANDARD_COMPLIANT)
#define INSANE_CPP_2X_STANDARD (INSANE_CPP_17_STANDARD | INSANE_CPP_2X_STANDARD_COMPLIANT)

#ifndef INSANE_CPP_STANDARD
#	if defined(INSANE_FORCE_UNKNOWN_CPP_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	elif !defined(__cplusplus)
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	elif(__cplusplus > 201703L) || defined(INSANE_FORCE_CPP_2X_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_2X_STANDARD
#	elif(__cplusplus >= 201703L) || defined(INSANE_FORCE_CPP_17_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_17_STANDARD
#	elif(__cplusplus >= 201402L) || defined(INSANE_FORCE_CPP_14_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_14_STANDARD
#	elif(__cplusplus >= 201103L) || defined(INSANE_FORCE_CPP_11_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_11_STANDARD
#	else
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	endif
#endif

#endif