#ifndef INSANE_CONFIGURATION_CPP_LANGUAGE_HPP_INCLUDE
#define INSANE_CONFIGURATION_CPP_LANGUAGE_HPP_INCLUDE

#include "macros.hpp"

#define INSANE_CPP_COMPILER_UNKNOWN     0x00
#define INSANE_CPP_COMPILER_LLVM_CLANG  0x01
#define INSANE_CPP_COMPILER_APPLE_CLANG 0x02
#define INSANE_CPP_COMPILER_GNU         0x04
#define INSANE_CPP_COMPILER_MSVC        0x08

#ifndef INSANE_CPP_COMPILER
#	if defined(INSANE_FORCE_UNKNOWN_CPP_COMPILER)
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_UNKNOWN
#	elif defined(__clang__) && !defined(__apple_build_version__)
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_LLVM_CLANG
#	elif defined(__clang__) && defined(__apple_build_version__)
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_LLVM_CLANG
#	elif defined(__GNUC__)
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_GNU
#	elif defined(_MSC_VER)
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_MSVC
#	else
#		define INSANE_CPP_COMPILER INSANE_CPP_COMPILER_UNKNOWN
#	endif
#endif

#define INSANE_CPP_NO_STANDARD_COMPLIANT 0x00
#define INSANE_CPP_11_STANDARD_COMPLIANT 0x01
#define INSANE_CPP_14_STANDARD_COMPLIANT 0x02
#define INSANE_CPP_17_STANDARD_COMPLIANT 0x04
#define INSANE_CPP_2X_STANDARD_COMPLIANT 0x08

#define INSANE_CPP_NO_STANDARD (INSANE_CPP_NO_STANDARD_COMPLIANT)
#define INSANE_CPP_11_STANDARD (INSANE_CPP_NO_STANDARD | INSANE_CPP_11_STANDARD_COMPLIANT)
#define INSANE_CPP_14_STANDARD (INSANE_CPP_11_STANDARD | INSANE_CPP_14_STANDARD_COMPLIANT)
#define INSANE_CPP_17_STANDARD (INSANE_CPP_14_STANDARD | INSANE_CPP_17_STANDARD_COMPLIANT)
#define INSANE_CPP_2X_STANDARD (INSANE_CPP_17_STANDARD | INSANE_CPP_2X_STANDARD_COMPLIANT)

#ifndef INSANE_CPP_STANDARD
#	if defined(INSANE_FORCE_UNKNOWN_CPP_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	elif !defined(__cplusplus)
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	elif(__cplusplus > 201703L) || defined(INSANE_FORCE_CPP_2X_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_2X_STANDARD
#	elif(__cplusplus >= 201703L) || defined(INSANE_FORCE_CPP_17_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_17_STANDARD
#	elif(__cplusplus >= 201402L) || defined(INSANE_FORCE_CPP_14_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_14_STANDARD
#	elif(__cplusplus >= 201103L) || defined(INSANE_FORCE_CPP_11_STANDARD)
#		define INSANE_CPP_STANDARD INSANE_CPP_11_STANDARD
#	else
#		define INSANE_CPP_STANDARD INSANE_CPP_NO_STANDARD
#	endif
#endif

#ifndef INSANE_CPP_HAS_FEATURE
#	if defined(__has_feature)
#		define INSANE_CPP_HAS_FEATURE(FEATURE) __has_feature(FEATURE)
#	else
#		define INSANE_CPP_HAS_FEATURE(FEATURE) 0
#	endif
#endif

#ifndef INSANE_HAS_CPP11_CONTEXPR
#	if INSANE_CPP_HAS_FEATURE(cxx_constexpr)
#		define INSANE_HAS_CPP11_CONSTEXPR INSANE_ENABLE
#	elif(INSANE_CPP_STANDARD & INSANE_CPP_11_STANDARD_COMPLIANT)
#		define ISNANE_HAS_CPP11_CONSTEXPR INSANE_ENABLE
#	else
#		define INSANE_HAS_CPP11_CONSTEXPR INSANE_DISABLE
#	endif
#endif

#ifndef CPP11_CONSTEXPR
#	if INSANE_HAS_CPP11_CONSTEXPR
#		define CPP11_CONSTEXPR constexpr
#	else
#		define CPP11_CONSTEXPR
#	endif
#endif

#endif